"""Initial frozen schema baseline"""
from alembic import op
import sqlalchemy as sa

revision = '20261006_01'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_resource', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('safety_accepted', sa.Boolean(), nullable=True),
    sa.Column('safety_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('safety_policy_version', sa.String(length=20), nullable=True),
    sa.Column('skin_type', sa.String(length=50), nullable=True),
    sa.Column('selected_goal', sa.String(length=100), nullable=True),
    sa.Column('skin_concerns', sa.JSON(), nullable=True),
    sa.Column('profile_context', sa.JSON(), nullable=True),
    sa.Column('tokens_balance', sa.Integer(), nullable=True),
    sa.Column('baseline_checkins_count', sa.Integer(), nullable=True),
    sa.Column('reset_token_hash', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('reset_token_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reset_token_hash'), 'users', ['reset_token_hash'], unique=False)
    op.create_table('captures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('view', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=False),
    sa.Column('image_blob_name', sa.String(length=500), nullable=True),
    sa.Column('server_version', sa.String(length=50), nullable=False),
    sa.CheckConstraint("(storage = 'not_persisted' AND image_blob_name IS NULL) OR (storage = 'azure_blob' AND image_blob_name IS NOT NULL AND state = 'accepted')", name='ck_capture_storage'),
    sa.CheckConstraint("source IN ('camera','upload') AND view = 'front'", name='ck_capture_origin'),
    sa.CheckConstraint("state IN ('accepted','rejected')", name='ck_capture_state'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captures_user_id'), 'captures', ['user_id'], unique=False)
    op.create_table('daily_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('unusual_conditions', sa.Boolean(), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_context_user_date')
    )
    op.create_index(op.f('ix_daily_contexts_user_id'), 'daily_contexts', ['user_id'], unique=False)
    op.create_table('doctor_patient_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('export_consent', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patient_access_access_token'), 'doctor_patient_access', ['access_token'], unique=True)
    op.create_index(op.f('ix_doctor_patient_access_doctor_id'), 'doctor_patient_access', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_access_patient_id'), 'doctor_patient_access', ['patient_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('active_ingredients', sa.JSON(), nullable=True),
    sa.Column('skin_concerns', sa.JSON(), nullable=True),
    sa.Column('usage_instructions', sa.Text(), nullable=True),
    sa.Column('frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('time_of_use', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('in_routine', sa.Boolean(), nullable=True),
    sa.Column('in_experiment', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('reward_redemptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reward_title', sa.String(length=255), nullable=False),
    sa.Column('tokens_spent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_redemptions_user_id'), 'reward_redemptions', ['user_id'], unique=False)
    op.create_table('doctor_review_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('access_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('recommendation', sa.String(length=30), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('patient_visible', sa.Boolean(), nullable=False),
    sa.Column('safety_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("recommendation IS NULL OR recommendation IN ('track','low_risk_self_care','doctor_review','urgent')", name='ck_doctor_recommendation'),
    sa.CheckConstraint("state IN ('pending','in_review','reviewed','follow_up_needed')", name='ck_doctor_review_state'),
    sa.ForeignKeyConstraint(['access_id'], ['doctor_patient_access.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'sequence', name='uq_doctor_review_sequence')
    )
    op.create_index(op.f('ix_doctor_review_actions_access_id'), 'doctor_review_actions', ['access_id'], unique=False)
    op.create_index(op.f('ix_doctor_review_actions_doctor_id'), 'doctor_review_actions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_review_actions_patient_id'), 'doctor_review_actions', ['patient_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('capture_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('quality_reference', sa.JSON(), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=False),
    sa.CheckConstraint("status IN ('measured','insufficient_quality','unavailable','failed')", name='ck_measurement_status'),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_id', 'algorithm_version', name='uq_measurement_capture_version')
    )
    op.create_index(op.f('ix_measurements_capture_id'), 'measurements', ['capture_id'], unique=False)
    op.create_index(op.f('ix_measurements_user_id'), 'measurements', ['user_id'], unique=False)
    op.create_table('product_intelligence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_product_intelligence_user_id'), 'product_intelligence', ['user_id'], unique=False)
    op.create_table('routine_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('schedule', sa.String(length=4), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('am_order', sa.Integer(), nullable=False),
    sa.Column('pm_order', sa.Integer(), nullable=False),
    sa.Column('active_am_product', sa.String(length=36), nullable=True),
    sa.Column('active_pm_product', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("frequency = 'daily'", name='ck_routine_frequency'),
    sa.CheckConstraint("schedule IN ('AM', 'PM', 'BOTH')", name='ck_routine_schedule'),
    sa.CheckConstraint("source = 'user_configured'", name='ck_routine_source'),
    sa.CheckConstraint('(active AND end_date IS NULL) OR (NOT active AND end_date IS NOT NULL AND end_date >= start_date)', name='ck_routine_end'),
    sa.CheckConstraint('am_order BETWEEN 0 AND 100 AND pm_order BETWEEN 0 AND 100', name='ck_routine_order'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_am_product', name='uq_routine_active_am'),
    sa.UniqueConstraint('active_pm_product', name='uq_routine_active_pm')
    )
    op.create_index(op.f('ix_routine_entries_product_id'), 'routine_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_routine_entries_user_id'), 'routine_entries', ['user_id'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('patient_visible', sa.Boolean(), nullable=False),
    sa.Column('timeline_item_id', sa.String(length=255), nullable=True),
    sa.Column('review_action_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('follow_up', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_action_id'], ['doctor_review_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_doctor_id'), 'clinical_notes', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_patient_id'), 'clinical_notes', ['patient_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('target_days', sa.Integer(), nullable=True),
    sa.Column('current_day', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('primary_concern', sa.String(length=100), nullable=True),
    sa.Column('redness_delta_percent', sa.Float(), nullable=True),
    sa.Column('texture_delta_percent', sa.Float(), nullable=True),
    sa.Column('hydration_delta_percent', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('engine_version', sa.Integer(), nullable=True),
    sa.Column('routine_entry_id', sa.String(length=36), nullable=True),
    sa.Column('intervention', sa.JSON(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('definition_snapshot', sa.JSON(), nullable=True),
    sa.Column('active_owner', sa.String(length=36), nullable=True),
    sa.CheckConstraint("engine_version IS NULL OR ((status = 'active' AND active_owner IS NOT NULL AND active_owner = user_id AND activated_at IS NOT NULL AND definition_snapshot IS NOT NULL) OR (status <> 'active' AND active_owner IS NULL))", name='ck_experiment_v2_owner'),
    sa.CheckConstraint("engine_version IS NULL OR (engine_version = 2 AND intervention IS NOT NULL AND routine_entry_id IS NOT NULL AND product_id IS NOT NULL AND source IS NOT NULL AND source = 'user_configured' AND status IS NOT NULL AND target_days IS NOT NULL AND status IN ('draft','active','completed','stopped','cancelled') AND target_days BETWEEN 7 AND 90)", name='ck_experiment_v2_definition'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['routine_entry_id'], ['routine_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_owner')
    )
    op.create_index(op.f('ix_experiments_user_id'), 'experiments', ['user_id'], unique=False)
    op.create_table('routine_adherence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('routine_entry_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.CheckConstraint("slot IN ('AM', 'PM')", name='ck_adherence_slot'),
    sa.CheckConstraint("source = 'user_reported'", name='ck_adherence_source'),
    sa.CheckConstraint("status IN ('completed', 'skipped')", name='ck_adherence_status'),
    sa.ForeignKeyConstraint(['routine_entry_id'], ['routine_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_entry_id', 'date', 'slot', name='uq_adherence_entry_day_slot')
    )
    op.create_index(op.f('ix_routine_adherence_routine_entry_id'), 'routine_adherence', ['routine_entry_id'], unique=False)
    op.create_index(op.f('ix_routine_adherence_user_id'), 'routine_adherence', ['user_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('date_str', sa.String(length=50), nullable=False),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('hydration_score', sa.Float(), nullable=True),
    sa.Column('texture_score', sa.Float(), nullable=True),
    sa.Column('redness_score', sa.Float(), nullable=True),
    sa.Column('observation', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_blob_name', sa.String(length=255), nullable=True),
    sa.Column('ai_vision_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('experiment_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_evaluations_experiment_id'), 'experiment_evaluations', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_evaluations_user_id'), 'experiment_evaluations', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrade prohibited; restore a rehearsed backup instead")
